### PR TITLE
🐛(front) fix "+ New" menu in read-only folders and virtual tabs

### LINKED ISSUE #577: Empty dropdown when clicking on New in read only folder
## Bug Report

**Problematic behavior**
When clicking on + New in a folder with read only accesses

Image

**Expected behavior/code**
The + New button should be disabled.

### PR DESCRIPTION
**Pull request by PanchoutNathan**
## Summary

- Always populate the "+ New" dropdown, even when the current folder is
  read-only or we're on a virtual tab (Recent, My Files, Shared with me,
  Starred). Previously the popover was empty because every entry was
  hidden on `!children_create`.
- When the user cannot create in place, fall back to creating the item
  in **My Files** (no parent). After a fallback creation:
  - folder → redirect into the new folder
  - file → redirect to the My Files view (a file is not a navigable
    route), new file pre-selected in the listing
- Add Playwright e2e tests covering the four branches of the new
  behavior (folder + file fallback from a read-only shared folder,
  folder creation from virtual tabs, and a sanity check that writable
  folders still create in place).

Fixes #577.

## Test plan

- [ ] Open a folder shared with you as Reader, click **+ New → Folder**,
      check you land inside the new folder under My Files.
- [ ] Same folder, **+ New → Text document**, check you land on
      `/explorer/items/my-files` with the new doc listed.
- [ ] Repeat from the Recent / Shared with me / Starred tabs.
- [ ] In a folder you own, **+ New → Folder** still creates in place
      with no redirect.
- [ ] `cd src/frontend/apps/e2e && yarn test create-fallback-to-my-files.spec.ts`

### CODE REVIEW

File: src/frontend/apps/drive/src/features/explorer/hooks/useCreateMenuItems.tsx [hunk 1]
```diff
@@ -36,8 +38,13 @@ export const useCreateMenuItems = ({
 }: UseCreateMenuItemsProps = {}): UseCreateMenuItemsReturn => {
   const { t } = useTranslation();
   const { item, itemId } = useGlobalExplorer();
-  const canCreateChildren = item ? item?.abilities?.children_create : true;
-  const isHidden = !canCreateChildren;
+  const router = useRouter();
+  const isOnMyFiles = isMyFilesRoute(router.pathname);
+  const canCreateHere = !!item?.abilities?.children_create;
```
Comment (NathanVss) [inline src/frontend/apps/drive/src/features/explorer/hooks/useCreateMenuItems.tsx]: Why are `!!` required?

File: src/frontend/apps/e2e/__tests__/app-drive/create-fallback-to-my-files.spec.ts [hunk 2]
```diff
@@ -0,0 +1,162 @@
...
+    const context = await browser.newContext();
+    const page = await context.newPage();
+    await use({ context, page });
+    await context.close();
+  },
+});
+
+const READ_ONLY_FOLDER = "ReadOnly folder";
+
+const setupReadOnlyFolderSharedWithB = async (userA: Page, userB: Page) => {
```
Comment (NathanVss) [inline src/frontend/apps/e2e/__tests__/app-drive/create-fallback-to-my-files.spec.ts]: `setupReadOnlyFolderSharedWithWebkitUser`

File: src/frontend/apps/e2e/__tests__/app-drive/create-fallback-to-my-files.spec.ts [hunk 3]
```diff
@@ -0,0 +1,162 @@
...
+  await clickToMyFiles(userA);
+  await createFolderInCurrentFolder(userA, READ_ONLY_FOLDER);
+  await navigateToFolder(userA, READ_ONLY_FOLDER, [
+    "My files",
+    READ_ONLY_FOLDER,
+  ]);
+  await shareCurrentItemWithWebkitUser(userA, "Reader");
+};
+
+const navigateBIntoReadOnlyFolder = async (page: Page) => {
```
Comment (NathanVss) [inline src/frontend/apps/e2e/__tests__/app-drive/create-fallback-to-my-files.spec.ts]: `navigateIntoReadOnlyFolder` instead?

File: src/frontend/apps/e2e/__tests__/app-drive/create-fallback-to-my-files.spec.ts [hunk 4]
```diff
@@ -0,0 +1,162 @@
...
+  for (const { go, label } of tabs) {
+    await go(page);
+
+    const folderName = `Tab folder ${label}`;
+    await createFolderViaNewMenu(page, folderName);
+
+    // Created in My files (no parent), and we are redirected into it
+    await expectExplorerBreadcrumbs(page, ["My files", folderName]);
+  }
+});
```
Comment (NathanVss) [inline src/frontend/apps/e2e/__tests__/app-drive/create-fallback-to-my-files.spec.ts]: Maybe use parameterized tests instead? It would provide more informations on fail

**Review by NathanVss — APPROVED** [review]
