### PR TITLE
🐛(frontend) Cancel active uploads when parent folder is deleted

### LINKED ISSUE #339: Stop uploading when the parent folder is deleted
## Bug Report

When you upload a large mass of files via a folder import and you delete the parent folder, the upload continues and when you restore the folder, not all the files are linked.

### PR DESCRIPTION
**Pull request by PanchoutNathan**
## Summary

- Track each uploading file's drop target folder
  via a Map (`fileDropTargetRef`)
- When a folder is deleted, selectively cancel only
  the uploads that were dropped into that folder,
  leaving other concurrent uploads unaffected
- Hook into both `useDeleteItem` and
  `ExplorerSelectionBar` deletion paths

### CODE REVIEW

File: src/frontend/apps/drive/src/features/explorer/hooks/useUpload.tsx
Comment (NathanVss) [inline src/frontend/apps/drive/src/features/explorer/hooks/useUpload.tsx:1]: Does not work if you delete a parent of the target folder.

- Create folder A
- Create folder B
- Go to folder B
- Drop files inside folder B
- Go up in folder A
- Delete folder A
- BUG: the uploading items are not stopped

File: src/frontend/apps/drive/src/features/explorer/hooks/useUpload.tsx [hunk 1]
```diff
@@ -592,7 +604,21 @@ export const useUploadZone = ({ item }: { item: Item }) => {
     return () => window.removeEventListener("beforeunload", unloadCallback);
   }, [uploadingState.step]);
 
+  const cancelUploadsForDeletedItems = useCallback(
+    (deletedIds: string[]) => {
+      if (!isProcessingRef.current) return;
+      const deletedSet = new Set(deletedIds);
+      for (const [filePath, dropTargetId] of fileDropTargetRef.current) {
```
Comment (NathanVss) [inline src/frontend/apps/drive/src/features/explorer/hooks/useUpload.tsx]: optimization: you are iterating over this entire set instead of using the map capabilities to retrieve the target id.

Instead, loop of `deleteIds` and `fileDropTargetRef.curent.get(deletedId)`. Greatly reduce the O().

File: src/frontend/apps/drive/src/features/explorer/hooks/useUpload.tsx
Comment (NathanVss) [inline src/frontend/apps/drive/src/features/explorer/hooks/useUpload.tsx]: I wonder: why is this required? Cancelling an item should just remove it from `uploadQueueRef` nope? 

This way, is `cancelledRef` still required?

File: src/frontend/apps/drive/src/features/explorer/hooks/useUpload.tsx [hunk 2]
```diff
@@ -236,6 +236,8 @@ export const useUploadZone = ({ item }: { item: Item }) => {
   const uploadQueueRef = useRef<FileUpload[]>([]);
   // Whether the upload processing loop is currently running
   const isProcessingRef = useRef(false);
+  // Map of filePath → drop target folder ID (for selective cancellation on deletion)
+  const fileDropTargetRef = useRef<Map<string, string>>(new Map());
```
Comment (NathanVss) [inline src/frontend/apps/drive/src/features/explorer/hooks/useUpload.tsx]: Why is this new ref needed as the target parentId is already stored in `uploadQueueRef`?

Comment (NathanVss) [reply src/frontend/apps/drive/src/features/explorer/hooks/useUpload.tsx]: It duplicates in multiple places the same data, leading to harder maintenability + risk of desync.

**Review by NathanVss — APPROVED** [review]
Much noïcer :)
