### PR TITLE
🐛(front) fix redirect after delete node in tree

### LINKED ISSUE #265: Deleting the current workspace
## Bug Report

**Problematic behavior**
When deleting the workspace we are in, the interface goes buggy.

**Expected behavior/code**
We should be redirected to our personal workspace.

### PR DESCRIPTION
**Pull request by PanchoutNathan**
## Purpose

close #265

### CODE REVIEW

File: src/frontend/apps/drive/src/features/explorer/components/tree/ExplorerTreeItemActions.tsx [hunk 1]
```diff
@@ -25,13 +27,46 @@ export const ExplorerTreeItemActions = ({
...
+      currentItemIsDeletedPath ||
+      (parentId && item.id === currentItem.id)
+    ) {
+      // If deleting an item in the current workspace or the current item itself, go to parent
+      redirectId = parentId || explorerContext.mainWorkspace?.id;
+    }
+
+    if (redirectId) {
+      router.push(`/explorer/items/${redirectId}`);
+    }
```
Comment (NathanVss) [inline src/frontend/apps/drive/src/features/explorer/components/tree/ExplorerTreeItemActions.tsx]: Easier to read?


```suggestion
    if (currentItemIsDeletedPath) {
      if (isWorkspace) {
        // If deleting a workspace and the current item is part of the workspace tree, redirect to the main workspace
        redirectId = explorerContext.mainWorkspace?.id;
      } else if (parentId && item.id === currentItem.id) {
        // If deleting an item in the current workspace or the current item itself, go to parent
        redirectId = parentId || explorerContext.mainWorkspace?.id;  
      }
    }    

    if (redirectId) {
      router.push(`/explorer/items/${redirectId}`);
    }
```

File: src/frontend/apps/drive/src/features/explorer/components/tree/ExplorerTreeItemActions.tsx [hunk 2]
```diff
@@ -25,13 +27,46 @@ export const ExplorerTreeItemActions = ({
...
+
+    // Determine the redirect target after deletion
+    let redirectId: string | undefined;
+
+    if (isWorkspace && currentItemIsDeletedPath) {
+      // If deleting a workspace and the current item is part of the workspace tree, redirect to the main workspace
+      redirectId = explorerContext.mainWorkspace?.id;
+    } else if (
+      currentItemIsDeletedPath ||
+      (parentId && item.id === currentItem.id)
```
Comment (NathanVss) [inline src/frontend/apps/drive/src/features/explorer/components/tree/ExplorerTreeItemActions.tsx:59]: It should always have a parentId in this case,nope?

File: src/frontend/apps/e2e/__tests__/app-drive/delete-item-in-tree.spec.ts [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+  await clearDb();
+  await login(page, "drive@example.com");
+  await page.goto("/");
+  await addChildrenFromTreeItem(page, "My workspace", "Test");
+  await toggleItemInTree(page, "My workspace");
+  await clickOnItemInTree(page, "Test");
+  await addChildrenFromTreeItem(page, "Test", "SubTest");
+  await clickOnItemInTree(page, "SubTest");
+  await deleteFolderInTree(page, "Test");
+  await checkTreeItemIsSelected(page, "My workspace");
```
Comment (NathanVss) [inline src/frontend/apps/e2e/__tests__/app-drive/delete-item-in-tree.spec.ts:29]: Maybe also check that the breadcrumbs shows the same folders? To make sure there is no discrepencies between tree and explorer

File: src/frontend/apps/e2e/__tests__/app-drive/delete-item-in-tree.spec.ts [hunk 4]
```diff
@@ -0,0 +1,40 @@
...
+  page,
+}) => {
+  await clearDb();
+  await login(page, "drive@example.com");
+  await page.goto("/");
+  await createWorkspace(page, "TestWorkspace");
+  await clickOnItemInTree(page, "TestWorkspace");
+  await createFolder(page, "TestFolder");
+  await deleteWorkspaceInTree(page, "TestWorkspace");
+  await checkTreeItemIsSelected(page, "My workspace");
```
Comment (NathanVss) [inline src/frontend/apps/e2e/__tests__/app-drive/delete-item-in-tree.spec.ts:44]: Ditto

File: src/frontend/apps/e2e/__tests__/app-drive/utils-common.ts [hunk 5]
```diff
@@ -1,7 +1,10 @@
 import { expect, Page } from "@playwright/test";
 import { exec } from "child_process";
-
-const ROOT_PATH = "../../../..";
+import path from "path";
+// We need to use __dirname to get the root path of the project
+// because Playwright runs tests in a different directory from the root
+// by default.
+const ROOT_PATH = path.join(__dirname, "/../../../../../..");
```
Comment (NathanVss) [inline src/frontend/apps/e2e/__tests__/app-drive/utils-common.ts:7]: Yep good

File: src/frontend/apps/e2e/__tests__/app-drive/delete-item-in-tree.spec.ts [hunk 6]
```diff
@@ -0,0 +1,40 @@
...
+}) => {
+  await clearDb();
+  await login(page, "drive@example.com");
+  await page.goto("/");
+  await addChildrenFromTreeItem(page, "My workspace", "Test");
+  await toggleItemInTree(page, "My workspace");
+  await clickOnItemInTree(page, "Test");
+  await addChildrenFromTreeItem(page, "Test", "SubTest");
+  await clickOnItemInTree(page, "SubTest");
+  await deleteFolderInTree(page, "Test");
```
Comment (NathanVss) [inline src/frontend/apps/e2e/__tests__/app-drive/delete-item-in-tree.spec.ts:28]: We might need to check the toast is shown and the message is correct
